CREATE TABLE tb_address (
    id NUMERIC GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cep VARCHAR(8) NOT NULL,
    street VARCHAR(255) NOT NULL,
    address_number VARCHAR(20) NOT NULL,
    address_state VARCHAR(19) NOT NULL,
    city  VARCHAR(255) NOT NULL,
    neighborhood VARCHAR(255) NOT NULL,
    user_id NUMBER NOT NULL,
    FOREIGN KEY (user_id) REFERENCES tb_user (id)
);